# Generated by Django 2.2.12 on 2021-01-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.TextField()),
                ('state', models.TextField()),
                ('stateacronym', models.TextField()),
                ('county', models.TextField()),
                ('city', models.TextField()),
                ('zip', models.TextField()),
                ('address', models.TextField()),
                ('agenttype', models.TextField(blank=True, default='ra')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
