# Generated by Django 2.2.12 on 2020-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=200)),
                ('bloguri', models.CharField(blank=True, max_length=200)),
                ('blogcategory', models.CharField(blank=True, max_length=200)),
                ('blogkeywords', models.TextField(blank=True)),
                ('blogpost', models.TextField(blank=True)),
            ],
        ),
    ]
