# Generated by Django 2.2.12 on 2020-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_blogdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogauthor',
            field=models.TextField(default='Jon Levy'),
        ),
    ]
