# Generated by Django 2.2.12 on 2020-05-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_blogauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogpostnational',
            field=models.TextField(blank=True),
        ),
    ]
