# Generated by Django 2.2.12 on 2020-04-13 18:55

from django.db import migrations, models
import djongo.models.fields
import templates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templatename', models.CharField(max_length=200)),
                ('sitemetas', models.TextField(blank=True)),
                ('sitelinks', models.TextField(blank=True)),
                ('sitescripts', models.TextField(blank=True)),
                ('sitestyle', models.TextField(blank=True)),
                ('siteheader', models.TextField(blank=True)),
                ('sitefooter', models.TextField(blank=True)),
                ('shortcodes', djongo.models.fields.ArrayField(blank=True, model_container=templates.models.Shortcode, model_form_class=templates.models.ShortcodeForm)),
                ('pages', djongo.models.fields.ArrayField(model_container=templates.models.Page, model_form_class=templates.models.PageForm)),
            ],
        ),
    ]
