# Generated by Django 2.2.12 on 2020-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='templatenotes',
            field=models.TextField(blank=True),
        ),
    ]
