# Generated by Django 2.2.12 on 2020-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cityngram',
            field=models.TextField(blank=True),
        ),
    ]
