# Generated by Django 2.2.12 on 2020-04-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='countyngram',
            field=models.TextField(blank=True),
        ),
    ]
