# Generated by Django 2.2.12 on 2020-07-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
