# Generated by Django 2.2.12 on 2020-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredagents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredagent',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registeredagent',
            name='fax',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registeredagent',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registeredagent',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registeredagent',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registeredagent',
            name='agency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registeredagent',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registeredagent',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
