# Generated by Django 2.2.12 on 2020-07-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredagents', '0002_auto_20200708_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredagent',
            name='contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='registeredagent',
            name='mail',
            field=models.TextField(blank=True),
        ),
    ]
