# Generated by Django 2.2.12 on 2020-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredagents', '0003_auto_20200709_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('searchkey', models.CharField(max_length=100)),
                ('searchvalue', models.TextField()),
            ],
        ),
    ]
