# Generated by Django 2.2.12 on 2020-07-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredagents', '0004_corporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredagent',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
