# Generated by Django 2.2.12 on 2020-08-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredagents', '0006_telecomcorps'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagent1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagent2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentaddress1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentaddress2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentaddress3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentcity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentemail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentext',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentfax',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentstate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagenttelephone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='alternateagentzip',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='dcagent1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='dcagent2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='dcagentaddress1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='dcagentaddress2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='dcagentaddress3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='dcagentcity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='dcagentstate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='dcagentzip',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='hqaddress1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='hqaddress2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='hqaddress3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='note1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='note2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='note3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='othertradename1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='othertradename2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='othertradename3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='telecomcorps',
            name='othertradename4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
