# Generated by Django 2.2.12 on 2020-12-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredagents', '0007_auto_20200804_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriername', models.TextField()),
                ('businessname', models.TextField(blank=True)),
                ('holdingcompany', models.TextField(blank=True)),
                ('hqaddress1', models.TextField(blank=True)),
                ('othertradename1', models.TextField(blank=True)),
                ('dcagent1', models.TextField()),
                ('dcagentaddress1', models.TextField()),
                ('dcagentcity', models.TextField()),
                ('dcagentstate', models.TextField()),
                ('dcagentzip', models.TextField(blank=True)),
                ('alternateagent1', models.TextField(blank=True)),
                ('alternateagenttelephone', models.TextField(blank=True)),
                ('alternateagentemail', models.TextField(blank=True)),
                ('alternateagentaddress1', models.TextField(blank=True)),
                ('alternateagentcity', models.TextField(blank=True)),
                ('alternateagentstate', models.TextField(blank=True)),
                ('alternateagentzip', models.TextField(blank=True)),
            ],
        ),
    ]
