# Generated by Django 2.2.12 on 2020-04-13 18:55

from django.db import migrations, models
import djongo.models.fields
import sites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=200)),
                ('templateid', models.IntegerField()),
                ('sitemetas', models.TextField(blank=True)),
                ('sitelinks', models.TextField(blank=True)),
                ('sitescripts', models.TextField(blank=True)),
                ('sitestyle', models.TextField(blank=True)),
                ('siteheader', models.TextField(blank=True)),
                ('sitefooter', models.TextField(blank=True)),
                ('blogcategory', models.CharField(blank=True, max_length=200)),
                ('shortcodes', djongo.models.fields.ArrayField(blank=True, model_container=sites.models.Shortcode, model_form_class=sites.models.ShortcodeForm)),
                ('location', djongo.models.fields.EmbeddedField(blank=True, model_container=sites.models.Location, model_form_class=sites.models.LocationForm, null=True)),
                ('pages', djongo.models.fields.ArrayField(model_container=sites.models.Page, model_form_class=sites.models.PageForm)),
            ],
        ),
    ]
