# Generated by Django 2.2.12 on 2020-06-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='national',
            field=models.BooleanField(default=True),
        ),
    ]
