# Generated by Django 2.2.12 on 2020-06-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_national'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='sitenotes',
            field=models.TextField(blank=True),
        ),
    ]
