# Generated by Django 2.2.12 on 2020-11-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20201116_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='siteauthor',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
